iot:
  gateway-id-list:
    - 'LIKEb2884'
    - 'LIKE92914'
  #  参数类型：开关量、瞬时量、累积量
  parameter-map:
    onoff:
      - 1013
      - 1014
      - 1015
      - 1016
      - 1017
      - 1018
      - 1019
      - 1020
      - 1021
      - 1022
      - 1023
      - 1024
      - 1025
      - 1026
      - 1027
      - 1028
      - 1029
      - 1030
      - 1031
      - 1032
      - 1033
      - 1034
      - 1035
      - 1036
      - 1037
      - 1038
      - 1039
      - 1040
      - 1041
      - 1042
      - 1043
      - 1044
      - 1045
      - 1046
      - 1047
      - 1048
      - 1049
      - 1050
      - 1051
      - 1052
    instant:
      - 1002
      - 1003
      - 1004
      - 1005
      - 1006
      - 1007
      - 1008
      - 1009
      - 1010
      - 1011
      - 1053
      - 1054
      - 1055
      - 1056
      - 1057
      - 1058
      - 1059
      - 1060
      - 1062
      - 1063
      - 1064
      - 1065
      - 1066
      - 1067
      - 1068
      - 1079
      - 1071
      - 1072
      - 1073
      - 1074
      - 1075
      - 1076
    accumulate:
      - 1012
      - 1061
      - 1070
